name: Run pre-commit checks


on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv (curl method)
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Cache uv virtualenv
      uses: actions/cache@v4
      with:
        path: .venv
        key: uv-venv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          uv-venv-${{ runner.os }}-

    - name: Install pre-commit tool with uv
      run: |
        uv tool install --with pre-commit-uv pre-commit
        
    - name: Setup pre-commit cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      
    - run: pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
      shell: bash
